name: "Deploy to ECS"
on:
  push:
    branches:
      - dev

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: Development
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Show Vars
        run: echo ${{ vars.AWS_CREDENTIALS_AUDIENCE }}
      - name: Configure AWS Crendetials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          # audience: ${{ vars.AWS_CREDENTIALS_AUDIENCE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - name: Build, tag and push docker image to AWS ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: galdoway.dev/web-app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t galdoway.dev/web-app:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
